### ISSUE TITLE
PAPI 2.10.10 breaks Vault expansion on Mohist 1.12.2

### ISSUE THREAD

**Issue by Agrrox** [PlaceholderAPI/Vault-Expansion#27]
**plugin list:**
```
Name : LuckPerms
Version : 5.3.3
---------
Name : Vault
Version : 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
---------
Name : Essentials
Version : 2.18.2.0
---------
Name : PlaceholderAPI
Version : 2.10.10
---------
Name : ProtocolLib
Version : 4.5.1
---------
Name : VentureChat
Version : 3.0.4
---------
```

**error message:**
<details><summary></summary>

```
[06:34:17 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[06:34:17 INFO]: [PlaceholderAPI] Fetching available expansion information...
[06:34:17 ERROR]: [PlaceholderAPI] Failed to load expansion class VaultExpansion - One of its properties is null which is not allowed!
[06:34:17 ERROR]: [PlaceholderAPI] 
 java.lang.NullPointerException: The expansion version is null!
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_252]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:166) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_252]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:461) ~[?:1.8.0_252]
	at java.util.stream.LongPipeline.sum(LongPipeline.java:419) ~[?:1.8.0_252]
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593) ~[?:1.8.0_252]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$3(LocalExpansionManager.java:327) ~[?:?]
	at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) [CraftTask.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:837) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

</details>

**Comment by Agrrox** [comment]
tested on Spigot rev 1.12.2 and everything works.

**Comment by refractored** [comment]
This works in the latest mohist buiilds
